# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDvWUqtmxrdsaHXQT-Vmaq_mWtMhQKsh
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Xato: Nolga bo'linish mumkin emas!"
    else:
        return x / y

def calculator():
    print("Bosh menyu:")
    print("1. Qo'shish")
    print("2. Ayirish")
    print("3. Ko'paytirish")
    print("4. Bo'lish")

    choice = input("Amalni tanlang (1/2/3/4): ")

    if choice in ['1', '2', '3', '4']:
        num1 = float(input("Birinchi sonni kiriting: "))
        num2 = float(input("Ikkinchi sonni kiriting: "))

        if choice == '1':
            print(f"Natija: {add(num1, num2)}")
        elif choice == '2':
            print(f"Natija: {subtract(num1, num2)}")
        elif choice == '3':
            print(f"Natija: {multiply(num1, num2)}")
        elif choice == '4':
            print(f"Natija: {divide(num1, num2)}")
    else:
        print("Noto'g'ri tanlov, iltimos qayta urinib ko'ring.")

if __name__ == "__main__":
    calculator()